name: "PV forecast"
version: latest
description: "Home Assistant add-on that provides PV forecasts"
init: false
slug: pv_forecast
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
hassio_api: true
docker_api: true
image: registry.dataspace.plaiful.org/hass/pv-forecast